pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo "Building the war"
            }
        }

        stage('Deploy to QA') {
            steps {
                echo "Deploying to QA"
            }
        }
        stage('Pull Docker Image') {
            steps {
                bat 'docker pull vijayalakshminirmal/datadrivenapitest2:1.0'
            }
        }

        stage('Run API Test Cases') {
            steps {
                bat 'docker run -v ${pwd}/results:/app/results vijayalakshminirmal/datadrivenapitest2:1.0'
            }
        }

        stage('Publish HTML Extra Report') {
            steps {
                publishHTML([
                    allowMissing: false,
                    alwaysLinkToLastBuild: false,
                    keepAll: true,
                    reportDir: 'results',
                    reportFiles: 'Datadriven.html',
                    reportName: 'Data driven HTML Extra report',
                    reportTitles: ''
                ])
            }
        }

        stage('Deploy to PROD') {
            steps {
                echo "Deploying to PROD"
            }
        }
    }
}